namePrefix: hub-
commonLabels:
  argocd.argoproj.io/secret-type: cluster
  role: infra
commonAnnotations:
  managed-by: argocd.argoproj.io
secretGenerator:
- name: hub-cluster-secret
  literals:
  - config={"tlsClientConfig":{"insecure":false}}
  - name=hub-cluster
  - server=https://kubernetes.default.svc
  
generatorOptions:
  disableNameSuffixHash: true
