apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: hub-one
  namespace: aap
spec:
  nginx_proxy_send_timeout: 120s
  gunicorn_content_workers: 2
  gunicorn_api_workers: 2
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  no_log: true
  file_storage_size: 100Gi
  image_pull_policy: IfNotPresent
  nginx_proxy_read_timeout: 120s
  gunicorn_timeout: 90
  nginx_client_max_body_size: 10m
  web:
    replicas: 1
  nginx_proxy_connect_timeout: 120s
  haproxy_timeout: 180s
  file_storage_access_mode: ReadWriteMany
  content:
    log_level: INFO
    replicas: 0
    resource_requirements:
      limits:
        cpu: 250m
        memory: 400mi
      requests:
        cpu: 150m
        memory: 400mi
  postgres_storage_requirements:
    limits:
      storage: 50Gi
    requests:
      storage: 8Gi
  api:
    log_level: INFO
    replicas: 1
    resource_requirements:
      limits:
        cpu: 250m
        memory: 400Mi
      requests:
        cpu: 150m
        memory: 400mi
  force_drop_db: false
  postgres_resource_requirements:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  redis:
    log_level: INFO
    replicas: 1
    resource_requirements:
      limits:
        cpu: 250m
        memory: 200mi
      requests:
        cpu: 100m
        memory: 200mi
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
  worker:
    replicas: 2
    resource_requirements:
      limits:
        cpu: 1000m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 3Gi
  storage_type: S3
  object_storage_s3_secret: s3-secret
  node_selector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - key: infra
      value: reserved
      effect: NoSchedule
  postgres_selector:
    node-role.kubernetes.io/infra: ""
  postgres_tolerations:
    - key: infra
      value: reserved
      effect: NoSchedule
