apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: rhcos-fileintegrity
  namespace: openshift-file-integrity
spec:
  nodeSelector:
    node.openshift.io/os_id: "rhcos"
  tolerations:
    - key: infra
      value: reserved
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      value: ""
      effect: NoSchedule
  config:
    gracePeriod: 86400
  debug: true
    
