---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-config-appset
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}-openshift-config'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        path: common-base/openshift-config
        targetRevision: HEAD
      destination:
        namespace: openshift-config
        server: '{{server}}'
      syncPolicy:

        syncOptions:
          - CreateNamespace=true
