---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-houston
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          env: 'dev'
      values:
        revision: HEAD
        env: dev
        namespace: true
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          env: 'prod'
      values:
        revision: stable
        env: prod
        namespace: false
  template:
    metadata:
      name: 'hello-{{name}}'
    spec:
      source:
        repoURL: 'https://github.com/r3dact3d/animated-bassoon'
        targetRevision: '{{values.revision}}'
        path: 'app/overlays/{{values.env}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace={{values.namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: 'hello-houston-{{name}}'
